=== gnardin/intERS/conf/simulation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

	<element name="simulation">
		<complexType>
			<sequence>
				<element name="numberOfRuns" type="positiveInteger" />
				<element name="randomSeeds" maxOccurs="1">
					<complexType>
						<choice minOccurs="0" maxOccurs="unbounded">
							<element name="seed" type="positiveInteger" />
						</choice>
					</complexType>
				</element>
				<element name="rsDirectory" type="string" />
				<element name="xmlFilename" type="string" />
				<element name="xsdFilename" type="string" />
				<element name="output" maxOccurs="1">
					<complexType>
						<sequence>
							<element name="directory" type="string" />
							<element name="fileExtorter" type="string" />
							<element name="fileObserver" type="string" />
							<element name="fileTarget" type="string" />
							<element name="fileAppend" type="boolean" />
							<element name="fieldSeparator" type="string" />
							<element name="writeEvery" type="positiveInteger" />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== gnardin/intERS/conf/simulation-random-extortion-1-20.xml
<?xml version="1.0" encoding="UTF-8"?>
<simulation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="simulation.xsd">
	<numberOfRuns>30</numberOfRuns>
	<randomSeeds>
		<seed>169868</seed>
		<seed>264938</seed>
		<seed>952330</seed>
		<seed>784304</seed>
		<seed>349822</seed>
		<seed>794420</seed>
		<seed>627685</seed>
		<seed>809965</seed>
		<seed>433048</seed>
		<seed>618492</seed>
		<seed>404017</seed>
		<seed>143477</seed>
		<seed>440910</seed>
		<seed>958559</seed>
		<seed>376096</seed>
		<seed>620606</seed>
		<seed>529685</seed>
		<seed>623491</seed>
		<seed>323362</seed>
		<seed>114713</seed>
		<seed>250453</seed>
		<seed>383124</seed>
		<seed>845896</seed>
		<seed>175638</seed>
		<seed>418133</seed>
		<seed>796957</seed>
		<seed>948785</seed>
		<seed>964121</seed>
		<seed>463313</seed>
		<seed>590965</seed>
		<seed>238052</seed>
		<seed>633181</seed>
		<seed>855904</seed>
		<seed>190382</seed>
		<seed>417486</seed>
		<seed>205726</seed>
		<seed>984803</seed>
		<seed>45171</seed>
		<seed>15691</seed>
		<seed>417851</seed>
		<seed>663664</seed>
		<seed>419709</seed>
		<seed>561328</seed>
		<seed>104574</seed>
		<seed>378269</seed>
		<seed>937425</seed>
		<seed>725181</seed>
		<seed>690659</seed>
		<seed>69236</seed>
		<seed>413566</seed>
		<seed>94017</seed>
		<seed>533961</seed>
		<seed>832222</seed>
		<seed>351755</seed>
		<seed>318961</seed>
		<seed>241578</seed>
		<seed>755574</seed>
		<seed>358986</seed>
		<seed>728039</seed>
		<seed>868898</seed>
		<seed>517640</seed>
		<seed>393482</seed>
		<seed>683047</seed>
		<seed>209967</seed>
		<seed>601655</seed>
		<seed>665722</seed>
		<seed>999346</seed>
		<seed>20152</seed>
		<seed>911332</seed>
		<seed>100194</seed>
		<seed>38546</seed>
		<seed>647819</seed>
		<seed>377286</seed>
		<seed>26759</seed>
		<seed>718449</seed>
		<seed>668995</seed>
		<seed>620114</seed>
		<seed>551202</seed>
		<seed>359654</seed>
		<seed>689350</seed>
		<seed>964768</seed>
		<seed>453672</seed>
		<seed>223312</seed>
		<seed>796990</seed>
		<seed>805428</seed>
		<seed>542273</seed>
		<seed>535734</seed>
		<seed>495417</seed>
		<seed>21070</seed>
		<seed>216962</seed>
		<seed>788216</seed>
		<seed>753724</seed>
		<seed>950456</seed>
		<seed>110925</seed>
		<seed>462126</seed>
		<seed>163691</seed>
		<seed>228943</seed>
		<seed>375258</seed>
		<seed>796537</seed>
		<seed>147426</seed>
		<seed>133909</seed>
		<seed>71800</seed>
		<seed>831611</seed>
		<seed>960488</seed>
		<seed>522191</seed>
		<seed>357278</seed>
		<seed>16584</seed>
		<seed>14774</seed>
		<seed>523059</seed>
		<seed>13901</seed>
		<seed>379567</seed>
		<seed>357007</seed>
		<seed>146155</seed>
		<seed>298223</seed>
		<seed>183739</seed>
		<seed>834743</seed>
		<seed>348493</seed>
		<seed>347843</seed>
		<seed>543638</seed>
		<seed>746837</seed>
		<seed>897348</seed>
		<seed>673638</seed>
		<seed>487483</seed>
		<seed>847484</seed>
		<seed>123254</seed>
		<seed>095059</seed>
		<seed>958958</seed>
		<seed>243635</seed>
		<seed>000111</seed>
		<seed>009177</seed>
		<seed>551866</seed>
		<seed>957456</seed>
		<seed>983788</seed>
		<seed>319890</seed>
		<seed>148832</seed>
		<seed>308715</seed>
		<seed>750527</seed>
		<seed>271334</seed>
		<seed>049736</seed>
		<seed>359694</seed>
		<seed>355882</seed>
		<seed>706982</seed>
		<seed>879269</seed>
		<seed>421145</seed>
		<seed>826579</seed>
		<seed>56095</seed>
		<seed>492582</seed>
		<seed>165781</seed>
		<seed>997317</seed>
		<seed>364793</seed>
		<seed>833948</seed>
		<seed>132253</seed>
		<seed>918655</seed>
		<seed>618238</seed>
		<seed>73722</seed>
		<seed>549739</seed>
		<seed>975245</seed>
		<seed>219878</seed>
		<seed>847962</seed>
		<seed>510980</seed>
		<seed>715295</seed>
		<seed>869032</seed>
		<seed>727942</seed>
		<seed>503511</seed>
		<seed>622757</seed>
		<seed>678399</seed>
		<seed>614436</seed>
		<seed>84884</seed>
		<seed>842090</seed>
		<seed>843380</seed>
		<seed>460142</seed>
		<seed>638627</seed>
		<seed>990806</seed>
		<seed>594052</seed>
		<seed>710428</seed>
		<seed>822418</seed>
		<seed>554541</seed>
		<seed>232619</seed>
		<seed>179696</seed>
		<seed>571126</seed>
		<seed>247394</seed>
		<seed>702755</seed>
		<seed>585027</seed>
		<seed>626961</seed>
		<seed>59762</seed>
		<seed>731182</seed>
		<seed>925185</seed>
		<seed>35008</seed>
		<seed>951060</seed>
		<seed>773147</seed>
		<seed>545988</seed>
		<seed>666356</seed>
		<seed>642180</seed>
		<seed>273930</seed>
		<seed>907954</seed>
		<seed>560917</seed>
		<seed>48543</seed>
		<seed>22667</seed>
		<seed>811370</seed>
		<seed>431668</seed>
		<seed>868564</seed>
	</randomSeeds>
	<rsDirectory>./intERS.rs</rsDirectory>
	<xmlFilename>./conf/scenario-random-extortion-1-20.xml</xmlFilename>
	<xsdFilename>./conf/scenario.xsd</xsdFilename>
	<output>
		<directory>./output/random-1-20/withProtection</directory>
		<fileExtorter>extorters.csv</fileExtorter>
		<fileObserver>observers.csv</fileObserver>
		<fileTarget>targets.csv</fileTarget>
		<fileAppend>false</fileAppend>
		<fieldSeparator>;</fieldSeparator>
		<writeEvery>50</writeEvery>
		<filePrefixAvg>cAvg</filePrefixAvg>
		<filePrefixSum>cSum</filePrefixSum>
		<classExtorterStat>intERS.statistics.DataSummaryGeneric</classExtorterStat>
		<classObserverStat>intERS.statistics.DataSummaryGeneric</classObserverStat>
		<classTargetStat>intERS.statistics.DataSummaryTarget</classTargetStat>
	</output>
</simulation>
